<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class CountrySeeder extends Seeder
{
    public function run()
    {
        foreach (self::$countries as $country) {
            DB::table('countries')->insert([
                'acronyms' => $country['acronyms'],
                'name' => $country['name'],
                'ddi'=> $country['ddi'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ]);
        }
    }
    
    public static $countries = [
        ['ddi' => '+55', 'acronyms' => 'BRA', 'name' => 'Brasil'],
        ['ddi' => '+93', 'acronyms' => 'AFG', 'name' => 'Afeganistão'],
        ['ddi' => '+355', 'acronyms' => 'ALB', 'name' => 'Albânia'],
        ['ddi' => '+213', 'acronyms' => 'ALG', 'name' => 'Argélia'],
        ['ddi' => '+376', 'acronyms' => 'AND', 'name' => 'Andorra'],
        ['ddi' => '+244', 'acronyms' => 'ANG', 'name' => 'Angola'],
        ['ddi' => '+54', 'acronyms' => 'ARG', 'name' => 'Argentina'],
        ['ddi' => '+61', 'acronyms' => 'AUS', 'name' => 'Austrália'],
        ['ddi' => '+43', 'acronyms' => 'AUT', 'name' => 'Áustria'],
        ['ddi' => '+1', 'acronyms' => 'BAH', 'name' => 'Bahamas'],
        ['ddi' => '+880', 'acronyms' => 'BAN', 'name' => 'Bangladesh'],
        ['ddi' => '+32', 'acronyms' => 'BEL', 'name' => 'Bélgica'],
        ['ddi' => '+591', 'acronyms' => 'BOL', 'name' => 'Bolívia'],
        ['ddi' => '+359', 'acronyms' => 'BUL', 'name' => 'Bulgária'],
        ['ddi' => '+855', 'acronyms' => 'CAM', 'name' => 'Camboja'],
        ['ddi' => '+1', 'acronyms' => 'CAN', 'name' => 'Canadá'],
        ['ddi' => '+1', 'acronyms' => 'CAY', 'name' => 'Ilhas Cayman'],
        ['ddi' => '+56', 'acronyms' => 'CHI', 'name' => 'Chile'],
        ['ddi' => '+86', 'acronyms' => 'CHN', 'name' => 'China'],
        ['ddi' => '+225', 'acronyms' => 'CIV', 'name' => 'Costa do Marfim'],
        ['ddi' => '+237', 'acronyms' => 'CMR', 'name' => 'Camarões'],
        ['ddi' => '+57', 'acronyms' => 'COL', 'name' => 'Colômbia'],
        ['ddi' => '+238', 'acronyms' => 'CPV', 'name' => 'Cabo Verde'],
        ['ddi' => '+506', 'acronyms' => 'CRC', 'name' => 'Costa Rica'],
        ['ddi' => '+385', 'acronyms' => 'CRO', 'name' => 'Croácia'],
        ['ddi' => '+53', 'acronyms' => 'CUB', 'name' => 'Cuba'],
        ['ddi' => '+45', 'acronyms' => 'DEN', 'name' => 'Dinamarca'],
        ['ddi' => '+1', 'acronyms' => 'DOM', 'name' => 'República Dominicana'],
        ['ddi' => '+593', 'acronyms' => 'ECU', 'name' => 'Equador'],
        ['ddi' => '+20', 'acronyms' => 'EGY', 'name' => 'Egito'],
        ['ddi' => '+34', 'acronyms' => 'ESP', 'name' => 'Espanha'],
        ['ddi' => '+44', 'acronyms' => 'ENG', 'name' => 'Inglaterra'],
        ['ddi' => '+358', 'acronyms' => 'FIN', 'name' => 'Finlândia'],
        ['ddi' => '+33', 'acronyms' => 'FRA', 'name' => 'França'],
        ['ddi' => '+49', 'acronyms' => 'GER', 'name' => 'Alemanha'],
        ['ddi' => '+504', 'acronyms' => 'HON', 'name' => 'Honduras'],
        ['ddi' => '+36', 'acronyms' => 'HUN', 'name' => 'Hungria'],
        ['ddi' => '+62', 'acronyms' => 'INA', 'name' => 'Indonésia'],
        ['ddi' => '+91', 'acronyms' => 'IND', 'name' => 'Índia'],
        ['ddi' => '+353', 'acronyms' => 'IRL', 'name' => 'Irlanda'],
        ['ddi' => '+964', 'acronyms' => 'IRQ', 'name' => 'Iraque'],
        ['ddi' => '+354', 'acronyms' => 'ISL', 'name' => 'Islândia'],
        ['ddi' => '+972', 'acronyms' => 'ISR', 'name' => 'Israel'],
        ['ddi' => '+39', 'acronyms' => 'ITA', 'name' => 'Itália'],
        ['ddi' => '+1', 'acronyms' => 'JAM', 'name' => 'Jamaica'],
        ['ddi' => '+81', 'acronyms' => 'JPN', 'name' => 'Japão'],
        ['ddi' => '+254', 'acronyms' => 'KEN', 'name' => 'Quênia'],
        ['ddi' => '+82', 'acronyms' => 'KOR', 'name' => 'Coreia do Sul'],
        ['ddi' => '+966', 'acronyms' => 'KSA', 'name' => 'Arábia Saudita'],
        ['ddi' => '+965', 'acronyms' => 'KUW', 'name' => 'Kuwait'],
        ['ddi' => '+218', 'acronyms' => 'LBA', 'name' => 'Líbia'],
        ['ddi' => '+961', 'acronyms' => 'LBN', 'name' => 'Líbano'],
        ['ddi' => '+212', 'acronyms' => 'MAR', 'name' => 'Marrocos'],
        ['ddi' => '+60', 'acronyms' => 'MAS', 'name' => 'Malásia'],
        ['ddi' => '+960', 'acronyms' => 'MDV', 'name' => 'Maldivas'],
        ['ddi' => '+52', 'acronyms' => 'MEX', 'name' => 'México'],
        ['ddi' => '+976', 'acronyms' => 'MGL', 'name' => 'Mongólia'],
        ['ddi' => '+258', 'acronyms' => 'MOZ', 'name' => 'Moçambique'],
        ['ddi' => '+505', 'acronyms' => 'NCA', 'name' => 'Nicarágua'],
        ['ddi' => '+234', 'acronyms' => 'NGR', 'name' => 'Nigéria'],
        ['ddi' => '+47', 'acronyms' => 'NOR', 'name' => 'Noruega'],
        ['ddi' => '+64', 'acronyms' => 'NZL', 'name' => 'Nova Zelândia'],
        ['ddi' => '+92', 'acronyms' => 'PAK', 'name' => 'Paquistão'],
        ['ddi' => '+507', 'acronyms' => 'PAN', 'name' => 'Panamá'],
        ['ddi' => '+595', 'acronyms' => 'PAR', 'name' => 'Paraguai'],
        ['ddi' => '+51', 'acronyms' => 'PER', 'name' => 'Peru'],
        ['ddi' => '+63', 'acronyms' => 'PHI', 'name' => 'Filipinas'],
        ['ddi' => '+48', 'acronyms' => 'POL', 'name' => 'Polônia'],
        ['ddi' => '+351', 'acronyms' => 'POR', 'name' => 'Portugal'],
        ['ddi' => '+850', 'acronyms' => 'PRK', 'name' => 'Coreia do Norte'],
        ['ddi' => '+1', 'acronyms' => 'PUR', 'name' => 'Porto Rico'],
        ['ddi' => '+974', 'acronyms' => 'QAT', 'name' => 'Catar'],
        ['ddi' => '+27', 'acronyms' => 'RSA', 'name' => 'África do Sul'],
        ['ddi' => '+7', 'acronyms' => 'RUS', 'name' => 'Rússia'],
        ['ddi' => '+221', 'acronyms' => 'SEN', 'name' => 'Senegal'],
        ['ddi' => '+65', 'acronyms' => 'SGP', 'name' => 'Singapura'],
        ['ddi' => '+386', 'acronyms' => 'SLO', 'name' => 'Eslovênia'],
        ['ddi' => '+252', 'acronyms' => 'SOM', 'name' => 'Somália'],
        ['ddi' => '+381', 'acronyms' => 'SRB', 'name' => 'Sérvia'],
        ['ddi' => '+41', 'acronyms' => 'SUI', 'name' => 'Suíça'],
        ['ddi' => '+421', 'acronyms' => 'SVK', 'name' => 'Eslováquia'],
        ['ddi' => '+46', 'acronyms' => 'SWE', 'name' => 'Suécia'],
        ['ddi' => '+963', 'acronyms' => 'SYR', 'name' => 'Síria'],
        ['ddi' => '+66', 'acronyms' => 'THA', 'name' => 'Tailândia'],
        ['ddi' => '+1', 'acronyms' => 'TTO', 'name' => 'Trinidad e Tobago'],
        ['ddi' => '+216', 'acronyms' => 'TUN', 'name' => 'Tunísia'],
        ['ddi' => '+90', 'acronyms' => 'TUR', 'name' => 'Turquia'],
        ['ddi' => '+971', 'acronyms' => 'UAE', 'name' => 'Emirados Árabes Unidos'],
        ['ddi' => '+380', 'acronyms' => 'UKR', 'name' => 'Ucrânia'],
        ['ddi' => '+598', 'acronyms' => 'URU', 'name' => 'Uruguai'],
        ['ddi' => '+1', 'acronyms' => 'USA', 'name' => 'Estados Unidos'],
        ['ddi' => '+58', 'acronyms' => 'VEN', 'name' => 'Venezuela'],
        ['ddi' => '+84', 'acronyms' => 'VIE', 'name' => 'Vietnã'],
        ['ddi' => '+967', 'acronyms' => 'YEM', 'name' => 'Iêmen'],
        ['ddi' => '+93', 'acronyms' => 'AFG', 'name' => 'Afeganistão'],
        ['ddi' => '+213', 'acronyms' => 'ALG', 'name' => 'Argélia'],
        ['ddi' => '+376', 'acronyms' => 'AND', 'name' => 'Andorra'],
        ['ddi' => '+244', 'acronyms' => 'ANG', 'name' => 'Angola'],
        ['ddi' => '+1', 'acronyms' => 'BAH', 'name' => 'Bahamas'],
        ['ddi' => '+1', 'acronyms' => 'CAY', 'name' => 'Ilhas Cayman'],
        ['ddi' => '+225', 'acronyms' => 'CIV', 'name' => 'Costa do Marfim'],
        ['ddi' => '+237', 'acronyms' => 'CMR', 'name' => 'Camarões'],
        ['ddi' => '+238', 'acronyms' => 'CPV', 'name' => 'Cabo Verde'],
        ['ddi' => '+506', 'acronyms' => 'CRC', 'name' => 'Costa Rica'],
        ['ddi' => '+385', 'acronyms' => 'CRO', 'name' => 'Croácia'],
        ['ddi' => '+53', 'acronyms' => 'CUB', 'name' => 'Cuba'],
        ['ddi' => '+1', 'acronyms' => 'DOM', 'name' => 'República Dominicana'],
        ['ddi' => '+593', 'acronyms' => 'ECU', 'name' => 'Equador'],
        ['ddi' => '+20', 'acronyms' => 'EGY', 'name' => 'Egito'],
        ['ddi' => '+44', 'acronyms' => 'ENG', 'name' => 'Inglaterra'],
        ['ddi' => '+358', 'acronyms' => 'FIN', 'name' => 'Finlândia'],
        ['ddi' => '+504', 'acronyms' => 'HON', 'name' => 'Honduras'],
        ['ddi' => '+36', 'acronyms' => 'HUN', 'name' => 'Hungria'],
        ['ddi' => '+353', 'acronyms' => 'IRL', 'name' => 'Irlanda'],
        ['ddi' => '+964', 'acronyms' => 'IRQ', 'name' => 'Iraque'],
        ['ddi' => '+354', 'acronyms' => 'ISL', 'name' => 'Islândia'],
        ['ddi' => '+972', 'acronyms' => 'ISR', 'name' => 'Israel'],
        ['ddi' => '+1', 'acronyms' => 'JAM', 'name' => 'Jamaica'],
        ['ddi' => '+254', 'acronyms' => 'KEN', 'name' => 'Quênia'],
        ['ddi' => '+82', 'acronyms' => 'KOR', 'name' => 'Coreia do Sul'],
        ['ddi' => '+966', 'acronyms' => 'KSA', 'name' => 'Arábia Saudita'],
        ['ddi' => '+965', 'acronyms' => 'KUW', 'name' => 'Kuwait'],
        ['ddi' => '+218', 'acronyms' => 'LBA', 'name' => 'Líbia'],
        ['ddi' => '+961', 'acronyms' => 'LBN', 'name' => 'Líbano'],
        ['ddi' => '+212', 'acronyms' => 'MAR', 'name' => 'Marrocos'],
        ['ddi' => '+60', 'acronyms' => 'MAS', 'name' => 'Malásia'],
        ['ddi' => '+960', 'acronyms' => 'MDV', 'name' => 'Maldivas'],
        ['ddi' => '+52', 'acronyms' => 'MEX', 'name' => 'México'],
        ['ddi' => '+976', 'acronyms' => 'MGL', 'name' => 'Mongólia'],
        ['ddi' => '+258', 'acronyms' => 'MOZ', 'name' => 'Moçambique'],
        ['ddi' => '+505', 'acronyms' => 'NCA', 'name' => 'Nicarágua'],
        ['ddi' => '+234', 'acronyms' => 'NGR', 'name' => 'Nigéria'],
        ['ddi' => '+47', 'acronyms' => 'NOR', 'name' => 'Noruega'],
        ['ddi' => '+64', 'acronyms' => 'NZL', 'name' => 'Nova Zelândia'],
        ['ddi' => '+92', 'acronyms' => 'PAK', 'name' => 'Paquistão'],
        ['ddi' => '+507', 'acronyms' => 'PAN', 'name' => 'Panamá'],
        ['ddi' => '+595', 'acronyms' => 'PAR', 'name' => 'Paraguai'],
        ['ddi' => '+51', 'acronyms' => 'PER', 'name' => 'Peru'],
        ['ddi' => '+63', 'acronyms' => 'PHI', 'name' => 'Filipinas'],
        ['ddi' => '+48', 'acronyms' => 'POL', 'name' => 'Polônia'],
        ['ddi' => '+351', 'acronyms' => 'POR', 'name' => 'Portugal'],
        ['ddi' => '+850', 'acronyms' => 'PRK', 'name' => 'Coreia do Norte'],
        ['ddi' => '+1', 'acronyms' => 'PUR', 'name' => 'Porto Rico'],
        ['ddi' => '+974', 'acronyms' => 'QAT', 'name' => 'Catar'],
        ['ddi' => '+27', 'acronyms' => 'RSA', 'name' => 'África do Sul'],
        ['ddi' => '+7', 'acronyms' => 'RUS', 'name' => 'Rússia'],
        ['ddi' => '+221', 'acronyms' => 'SEN', 'name' => 'Senegal'],
        ['ddi' => '+65', 'acronyms' => 'SGP', 'name' => 'Singapura'],
        ['ddi' => '+386', 'acronyms' => 'SLO', 'name' => 'Eslovênia'],
        ['ddi' => '+252', 'acronyms' => 'SOM', 'name' => 'Somália'],
        ['ddi' => '+381', 'acronyms' => 'SRB', 'name' => 'Sérvia'],
        ['ddi' => '+41', 'acronyms' => 'SUI', 'name' => 'Suíça'],
        ['ddi' => '+421', 'acronyms' => 'SVK', 'name' => 'Eslováquia'],
        ['ddi' => '+46', 'acronyms' => 'SWE', 'name' => 'Suécia'],
        ['ddi' => '+963', 'acronyms' => 'SYR', 'name' => 'Síria'],
        ['ddi' => '+66', 'acronyms' => 'THA', 'name' => 'Tailândia'],
        ['ddi' => '+1', 'acronyms' => 'TTO', 'name' => 'Trinidad e Tobago'],
        ['ddi' => '+216', 'acronyms' => 'TUN', 'name' => 'Tunísia'],
        ['ddi' => '+90', 'acronyms' => 'TUR', 'name' => 'Turquia'],
        ['ddi' => '+971', 'acronyms' => 'UAE', 'name' => 'Emirados Árabes Unidos'],
        ['ddi' => '+380', 'acronyms' => 'UKR', 'name' => 'Ucrânia'],
        ['ddi' => '+598', 'acronyms' => 'URU', 'name' => 'Uruguai'],
        ['ddi' => '+58', 'acronyms' => 'VEN', 'name' => 'Venezuela'],
        ['ddi' => '+84', 'acronyms' => 'VIE', 'name' => 'Vietnã'],
        ['ddi' => '+967', 'acronyms' => 'YEM', 'name' => 'Iêmen']
    ];

}
